### PR TITLE
add support for redox os, windows and macos

### LINKED ISSUE #5: Windows support
can you add?

### LINKED ISSUE #7: redox support [feature request]
https://www.redox-os.org/

### PR DESCRIPTION
**Pull request by Hezuikn**
untested
closes #7 closes #5

### CODE REVIEW

**Comment by Hezuikn** [comment]
LGTM https://www.youtube.com/watch?v=9yRR24MFLCM

**Comment by ben0x539** [comment]
hm, i dont want to depend on a crate that just has a bunch of unsafe ffi calls, that takes the fun out of it imo.

does cfg_if make it a lot nicer than doing raw cfg things?

guess I gotta figure out how to test on redox heh

**Comment by Hezuikn** [comment]
cfg_if brakes rustfmt

**Comment by Hezuikn** [comment]
all ffi is implicitly unsafe

**Pull request closed without merging**
